documentacao-ustore/ucloud-rtd-manual

Manuais/usr-manual.rst
Revisando gramática e termos repetidos na jornada do utilizador até o tópico de templates.
=> revisando jornada utilizador ate templates

Press-Release/2023.06.09.rst
=> Revisando conteúdo publicado press

Press-Release/2023.06.09.rst
=> Inserindo conteúdo final no press 3

index.rst
=> Ocultando apresentação press 2023.06.16

Press-Release/2023.06.16.rst, index.rst
Índice apresenta título e frase, deu bug. 
Exclui linha e inseri linhas.
=> Corrigindo negrito no cabeçalho e índice

MEnglish/mangue-usuario.eng.rst
Incluindo mais um tópico no documento
=> avançando até a linha 1420

Press-Release/2023.06.16.rst, index.rst
Finalizando conteúdo press 4 e inserindo o press no índice de apresentação.
=> Atualizando conteúdo press release 4 e índice

Press-Release/2023.06.16.rst
=> Corrigindo inconsistência última atualização

MEnglish/mangue-usuario.eng.rst
inserindo novos tópicos até consolidated report item C. By Tags
=> atualizando mangue eng até a linha 1999

MEnglish/mangue-usuario.eng.rst, Manuais/mangue-usuario.rst
mangue eng até a linha 2009
mangue ptbr ajustando estrutura de bullets, negritos e inserção de ícones
=> atualizando mangues ptbr e eng

Press-Release/2023.06.23.rst
=> Revisão da publicação conteúdo 5 press release

Manuais/mangue-usuario.rst
=> Adicionando chamada banco imagens 198 a 217

Manuais/mangue-usuario.rst
última revisão negrito, itálico e ortografia.
=> Refinamento conteúdo mangue.io PtBr l.3422

MEnglish/mangue-usuario.eng.rst
ajustando estrutura, imagens, notas e icones
=> refinando mangue eng

Manuais/mangue-usuario.rst
do início até o final, revisão geral de tudo.
=> Atualização geral mangue PtBr l. 3870

MEnglish/mangue-usuario.eng.rst
ajustando estrutura de hyperlinks, título de níveis 3 e nota + texto.
=> testando estrutura de hyperlinks e notas

Manuais/mangue-usuario.rst
Negritos;
Tabulações;
Itálicos;
Correções ortográficas.
=> Finalizando refinamento da revisão Mangue PtBr

Manuales/mangue-usuario.spa.rst
Publicando Mangue ESP até a linha 1102, finalizando o tópico de Workloads.
=> mangue spa até catálogo

Press-Release/2023.05.26.rst, Press-Release/2023.06.16.rst, Press-Release/2023.06.16.spa.rst
Press release 2023.06.16 e 2023.05.26.
Nota de Prensa 2023.06.16.
=> Adicionando conteúdo SPA e correção PtBr

Press-Release/2023.06.16.rst, Press-Release/2023.06.16.spa.rst
Organizando as chamadas para versão internacionalizada em cada um dos documentos:
Press release e Nota de prensa
=> Publicando versão PtBr e SPA hyperlink

Press-Release/2023.06.02.spa.rst, Press-Release/2023.06.09.rst, Press-Release/2023.06.09.spa.rst
nota de prensa spa
inserindo conteúdo 
hyperlink para doc.PtBr
=> Adicionando novo conteúdo nota 2023.06.02

Press-Release/2023.05.26.rst, Press-Release/2023.06.02.spa.rst, Press-Release/2023.06.23.rst, Press-Release/2023.06.23.spa.rst
=> Revisando detalhes e hyperlink

Press-Release/2023.06.09.rst, Press-Release/2023.06.16.spa.rst, Press-Release/2023.06.23.eng.rst, Press-Release/2023.06.23.rst, Press-Release/2023.06.23.spa.rst
Press release
PtBr SPA ENG
inserindo hyperlink English
=> Rosinha atualizando

Press-Release/2023.05.26.rst
2023.05.26 
press release
adicionar spa
=> Adicionando hyperlink spa

Press-Release/2023.05.26.eng.rst, Press-Release/2023.06.23.eng.rst
=> Refinamento revisão press release eng

MEnglish/dci.eng.rst, MEnglish/mangue-usuario.eng.rst, MEnglish/ucloud-user.eng.rst, MEnglish/usavings-usuario.eng.rst, Manuais/dci-manual.rst, Manuais/mangue-usuario.rst, Manuais/usavings-usuario.rst, Manuais/usr-manual.rst, Manuales/dci.spa.rst, Manuales/mangue-usuario.spa.rst, Manuales/ucloud-usuario.spa.rst, Manuales/usavings-usuario.spa.rst
=> Rosinha inserindo hyperlinks internacionalização

Manuais/usr-manual.rst
em substituição ao menu containers
=> Atualizando o menu Provedor de Contas título

MEnglish/tickets.eng.rst, Manuales/llamadas.spa.rst, index.rst
=> Inserindo teste de chamada no índice

MEnglish/tickets.eng.rst
=> Modificando nível de título inicial

MEnglish/dci.eng.rst, MEnglish/mangue-usuario.eng.rst, MEnglish/ucloud-user.eng.rst, MEnglish/usavings-usuario.eng.rst, Manuais/mangue-usuario.rst, Manuales/dci.spa.rst, Manuales/llamadas.spa.rst, Manuales/mangue-usuario.spa.rst, Manuales/ucloud-usuario.spa.rst, Manuales/usavings-usuario.spa.rst, index.rst
Documentação Ustore BR
inserir docs traduzidos e seus menus e submenus devem ser apresentados.
=> Rosinha modifica índice página entrada

Manuais/dci-manual.rst, Manuais/mangue-usuario.rst, Manuais/usavings-usuario.rst, Manuais/usr-manual.rst
Todos os títulos dos docs alterados para maiúscula nome produto
=> Rosinha atualiza item Produtos 

MEnglish/dci.eng.rst, MEnglish/mangue-usuario.eng.rst, MEnglish/ucloud-user.eng.rst, MEnglish/usavings-usuario.eng.rst, Manuales/dci.spa.rst, Manuales/mangue-usuario.spa.rst, Manuales/ucloud-usuario.spa.rst, Manuales/usavings-usuario.spa.rst
ação melhoria índice geral da página.
=> Rosinha trabalhando Documentação Ustore Br 

index.rst
=> testando publicação chamados em cx alta

MEnglish/tickets.eng.rst, Manuais/chamados.rst, Manuales/llamadas.spa.rst, index.rst
Documentação Ustore BR
ambiente online
índice
=> Procedendo alteração completa chamados

index.rst
Documentação Ustore BR
índice
textos
=> Atualizando índice e textos pág entrada doc.online

MEnglish/dci.eng.rst, MEnglish/mangue-usuario.eng.rst, MEnglish/ucloud-user.eng.rst, MEnglish/usavings-usuario.eng.rst, Manuais/dci-manual.rst, Manuais/mangue-usuario.rst, Manuais/usavings-usuario.rst, Manuais/usr-manual.rst, Manuales/dci.spa.rst, Manuales/mangue-usuario.spa.rst, Manuales/ucloud-usuario.spa.rst, Manuales/usavings-usuario.spa.rst, index.rst
=> Modificando a apresentação dos docs índice geral

Manuais/dci-manual.rst, index.rst
=> Ajustando índice

Release-Notes/nota-de-lançamento-ucloud-2022-jun.jul.ago.rst, Release-Notes/notas-de-publicación-ucloud-2022-jun.jul.ago.rst, Release-Notes/press-release-ucloud-2022-jun.jul.aug.rst, Release-Notes/publicación-trimestral-ucloud-2022-jun.jul.ago.rst, Release-Notes/release-notes-ucloud-2022-03-20.rst, Release-Notes/release-notes-ucloud-2022-07-01.rst, Release-Notes/release-notes.ing-ucloud-2022-mayo.rst, Release-Notes/release-notes.spa-ucloud-2022-mayo.rst, Release-Notes/release-ucloud-2022-jun-jul-ago.rst, Release-Notes/release.ing-ucloud-2022-jun.jul.aug.rst, index.rst
inserindo:
cabeçalho tradução
título
=> Rosinha atualiza release note

index.rst
inserindo conteúdo para publicar novos docs.
=> Atualizando índice campo Release Note

Release-Notes/nota-de-lançamento-ucloud-2022-jun.jul.ago.rst, Release-Notes/press-release-ucloud-2022-jun.jul.aug.rst
=> Adicionando correções 2022.06-08 ptbr spa eng

Release-Notes/publicación-trimestral-ucloud-2022-jun.jul.ago.rst, Release-Notes/release-notes-ucloud-2022-03-20.rst, Release-Notes/release-notes-ucloud-2022-07-01.rst, Release-Notes/release-notes.ing-ucloud-2022-mayo.rst, Release-Notes/release-notes.spa-ucloud-2022-mayo.rst, Release-Notes/release-ucloud-2022-jun-jul-ago.rst, Release-Notes/release.ing-ucloud-2022-jun.jul.aug.rst
Nova estrutura apresentação
Documentação Ustore BR
=> Rosinha finalizando adequação docs Release note

Manuais/dci-manual.rst
última atualização deste projeto DCI.
=> Adicionando final manual DCI

Manuais/dci-manual.rst, figuras/fig_dci/desktop.ini
=> Rosinha pós revisão DCI

Manuales/dci.spa.rst
Foi realizada uma nova leitura, revisão e correção da tradução do Manual do DCI em Língua Espanhola; (20/10/2023)
=> Revisão publicação DCI SPA

Manuais/usr-manual.rst
=> Atualizando a raiz títulos e subtítulos por níveis

Manuais/usr-manual.rst
Após publicar a nova raiz do ucloud, alguns dados precisaram de modificações.
=> Revisão publicado até linha 3515 ucloud

Manuais/usr-manual.rst
=> Adicionando conteúdo Auto Assessment PtBr

Manuais/usr-manual.rst
REvisado novamente raiz ucloud menu segurança.
correções.
=> Adicionando alterações pós revisão ucloud, l.6730

Manuais/usr-manual.rst
Adicionando alterações no conteúdo pós revisão.
=> Alterando pós revisão ucloud linhas 934 até 3200

Manuais/usr-manual.rst
Seguindo na revisão da atualização da raiz do ucloud + hyperlinks + últimas adições Menu Segurança.
=> Adicionar alteração pós revisão l.3439-6875 uCloud

Manuais/usr-manual.rst, figuras/botao.txt, figuras/icones.txt
Vários hyperlinks quebrados estão corrigidos após este PR.
Revisão lista dos ícones e botões.
uCloud
=> Rosinha corrige hyperlinks ucloud

Manuais/usr-manual.rst
uCloud, menu Ethical Phishing.
=> Correção em alguns subtítulos que estavam ausentes

MEnglish/ucloud-user.eng.rst
corrigindo letras maiúsculas em subtítulos
removendo tópicos escondidos
inserindo ---- na divisão de menus
=> corrigindo subtítulos ucloud ENG

Manuais/usr-manual.rst
Na análise da raiz uCloud existem modificações nos níveis dos subtítulos do menu financeiro e outros.
=> Revisão dos menus uCloud: VDc até Flavors

MEnglish/ucloud-user.eng.rst, Manuais/usr-manual.rst
**uCloud ENG**
Ajuste do index menu financeiro
**uCloud PTBr**
Inserção dos títulos e subtítulos do tópico de termo de responsabilidade
=> menu financeiro ENG e termo de resp PTBr

Manuais/usr-manual.rst
Releitura da raiz comparando com o portal uCloud, resulta neste aprimoramento de conteúdo.
=> Aprimorando raiz menu ucloud novo conteúdo

Manuais/usr-manual.rst
=> Atualizando linha contínua divide subtítulos

Manuales/ucloud-usuario.spa.rst
Raiz atualizada - Presentación - Introducción - Acceso a la plataforma uCloud - Dashboard
=> Atualização da Raiz ucloud SPA L548.

Manuales/ucloud-usuario.spa.rst
Atualização da raíz do manuel ucloud em SPA - Menú Administración (parte 01) Switch Roles;  Cuenta *(Account)*; Cuentas ;  Usuarios; Visualizando un usuario; Creando un Nuevo Usuario.
=> Atualização raíz ucloud SPA - Menú Administración

Manuales/ucloud-usuario.spa.rst
Atualização do manuel ucloud SPA - Menú Administración (Parte2) - Menú Configuración (Parte1)
=> New thales - 2 commits Iguales

Manuales/ucloud-usuario.spa.rst
Insideridos no ambiente a raíz dos menus: Menú Configuración (Parte2) - Menú Seguridad - Menú Maquinas Virtuales - Menú Orquestador - Menú Scaling Groups - Menú Base de Datos - Menú Virtual Datacenters -
=> Atualização Raíz Ucloud L-2152

Manuales/ucloud-usuario.spa.rst
Atualização da raíz do Manual uCloud em SPA - Menú Financiero - Menú Orden de Servicio - Menú Recomendaciones -  Menú Containers - Menú Hosts - Menú Redes;
=> Atualição raíz ucloud SPA L-2766

Manuais/usr-manual.rst
Inserindo submenu "Cores: Modo escuro".
=> Adicionando subtítulo menu uCloud nova raiz.

Manuales/ucloud-usuario.spa.rst
Atualização e Finalização da Raíz uCloud SPA - Menú Storage - Menú Modelos - Menú Flavors - Menú Workflows - Menú Tareas - Menú Inventario de Recursos - Menú Colores y Personalización;
=> Finalização da Raiz ucloud SPA

Manuales/ucloud-usuario.spa.rst
Depois da publicação realizei uma leitura na raíz e percebi alguns detalhes que precisavam ser corrigidos. Foram realizadas todas as alterações necessárias;
=> Atualização uCloud SPA Correções

MEnglish/ucloud-user.eng.rst
inserção de novos subtítulos no ucloud eng
=> atualizando index ucloud eng

MEnglish/dci.eng.rst, MEnglish/mangue-usuario.eng.rst, MEnglish/tickets.eng.rst, MEnglish/usavings-usuario.eng.rst
ajustando formato de datas nos manuais ENG do
Mangue
uSavings
Chamados
DCI
=> ajustando formato de datas ENG

Manuales/mangue-usuario.spa.rst
Atualização do Manuel do Mangue em SPA - Parte 01;
=> Correções do Mangue SPA Part1

index.rst
1. Adicionando o documento release consolidado 2023.06-12 no diretório Release Notes, publicar no ambiente online;
2. Retifica informações no item 4 Suporte na apresentação do ambiente e seus documentos.
=> Rosinha direciona doc. 2023.06-12 no diretório release notes

Release-Notes/2023.06-12-ustore-geral.rst
algumas tabelas precisaram de correção;
negritos foram inseridos nos títulos;
pequenas retificações de pontuação.
=> Subindo após revisão do documento release consolidado

Release-Notes/2023.06-12-ustore-geral.rst
Na terceira leitura percebi que deveria ampliar o texto da apresentação da Plataforma Mangue.io e suas features.
=> Adicionando texto apresentação mangue

Release-Notes/2023.06-12-ustore-geral.rst
=> Adicionando quarta revisão pontuação nas tabelas

Manuales/mangue-usuario.spa.rst
Segunda parte da atualização do manual do mangue em SPA, verificação de erros e complementos;
=> Atualização Manual Mangue SPA PT2

Manuales/mangue-usuario.spa.rst
Continuação da revisão/atualização do manual do Mangue SPA - Parte 03.
=> Revisão Manual Mangue SPA PT3

Manuais/usr-manual.rst
Correção dos erros de publicação do relatório de custo relacional de produto - CRP
=> Correção dos erros de publicação CRP

Release-Notes/2023.06-12-ustore-geral.rst
. Add nível título plataforma usavings e portal uCloud;
. novas implementações apresentadas em tabela numerada, para uSavings e uCloud;
. distribuição em tópicos uCloud Financeiro, Operação e Segurança.
. inserção das tabelas para add informações de cada tópico.
=> Add alterações textuais no uSavings e uCloud

Manuales/mangue-usuario.spa.rst
Atualização do manual do Mangue em SPA;
=> Revisão Manual Mangue SPA - Parte 04 -

Manuais/usr-manual.rst
Adição do ícone que representa o botão "Próximo" no relatório de Custo Relacional de Produto - CRP
=> Atualização do Botão "Próximo" CRP

Manuales/mangue-usuario.spa.rst
Atualização do Manual do Mangue em Espanhol, novas atualizações;
=> Atualização Manual Mangue SPA - Parte 05

Release-Notes/2023.06-12-ustore-geral.rst
=> Corrigindo tabela Neptune

Release-Notes/2023.06-12-ustore-geral.rst
Atualização da Tabela = Ethical Phishing - Utilizador
=> Atualização Tabela Phishing Utilizador

Release-Notes/2023.06-12-ustore-geral.rst
=> Inserindo hyperlink auto assessment

Release-Notes/2023.06-12-ustore-geral.rst
=> Alterando extensão 2 imagens crp e franquia ucloud

Manuais/usr-manual.rst
Manual uCloud 
Regras do Financeiro
Regra de Faturamento
=> Inserindo novo item Financeiro Regra de Faturamento

Release-Notes/2023.06-12-ustore-geral.rst
Manual ucloud abrimos novo nível dentro do menu financeiro 
Abriga Regra do financeiro > regra de faturamento
Adicionado hyperlink de acesso ao manual.
=> Inserindo hyperlink regra de faturamento no manual ucloud

Release-Notes/2023.06-12-ustore-geral.rst
Release Notes Consolidado 2023.06-12
=> Dimensionando imagem CRP por dia

Manuales/ucloud-usuario.spa.rst
Atualização da Raiz do Manual uClod com o título "Regra de Faturação"
=> Atualização da Raiz uCloud SPA

Manuais/usr-manual.rst
Publicação do documento: Regra de Faturamento - uCloud.
=> Publicação Doc Regra de Faturamento

Manuais/usr-manual.rst
Atualização de ícones no documento - Regra de Faturamento
=> Atualizando ícones - regra Faturamento

MEnglish/ucloud-user.eng.rst
corrigindo duas imagens de account
ajustando introdução de account
inserindo chamadas de ícones no final do doc
=> corrigindo imagens e intro

Manuales/mangue-usuario.spa.rst
Alterações no Manual do Mangue em SPA
=> Revisão Mangue PT07

Manuais/usr-manual.rst
=> Revisão Card-Credenciais

Manuales/mangue-usuario.spa.rst
Atualização do Manual do Mangue em SPA;
=> Revisão do Mangue

Manuales/ucloud-usuario.spa.rst
Add texto do Informe Tendencia de Facturación no Menu Financeiro. uCloud - SPA
=> Texto Informe Tendencia de Facturación

Manuales/ucloud-usuario.spa.rst
Introdução da tradução revisada no Informe Consolidado de Facturación
=> Informe consolidado de facturación SPA

MEnglish/ucloud-user.eng.rst
corrigindo imagens de png para PNG
corrigindo negrito
=> revisao crp ucloud eng

MEnglish/ucloud-user.eng.rst
inserindo relatório consolidado de faturamento no ucloud eng
de inicio banco de imagem em portugues, a ser atualizado
=> inserindo consolidado de faturmento eng

MEnglish/ucloud-user.eng.rst
correções em custo relacional do produto no ucloud inglês
=> ajustes em crp ucloud eng

Press-Release/2024.03.15.rst
correção textual, inserindo campo importante.
=> Corrigindo após revisão

Press-Release/2024.03.15.rst
=> Substituição de 2 frases do conteúdo no press release Oracle

Manuales/ucloud-usuario.spa.rst
Add texto em SPA do relatório de Costos Cadenciados
=> Costos Cadenciados - Traducción para SPA
